name: Test

on:
  push:
  workflow_call:
  pull_request:

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/setup-test-env
    - run: yarn build
    - run: test/test.sh
    - run: yarn jest

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/setup-test-env
    - run: yarn lint
