name: Test

on:
  push:
  workflow_call:

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-test-env
      - run: pnpm build
        shell: nix develop -c bash -eo pipefail -l {0}
      - run: test/test.sh
        shell: nix develop -c bash -eo pipefail -l {0}
      - run: pnpm jest
        shell: nix develop -c bash -eo pipefail -l {0}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-test-env
      - run: pnpm lint
        shell: nix develop -c bash -eo pipefail -l {0}
